Aiven
navikt/syfosminfotrygd pull request #122
Opened 2022-01-11 13:37 UTC by tiafiring

2022-01-11 16:04 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/model/OpprettOppgaveKafkaMessage.kt
> +    private val messageId: String,
Må fjerne 'private' ellers blir det bare '{}' som blir skrevet til kafka

2022-01-11 16:05 UTC, andreasDev requested changes
sjekk kommentaren i OpprettOppgaveKafkaMessage

2022-01-12 05:31 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/model/OpprettOppgaveKafkaMessage.kt
> +    private val messageId: String,
oj, good catch! Ser at jeg bruker en avrotype her også, den skal jo helst bort.

2022-01-12 09:09 UTC, andreasDev approved these changes

2022-01-12 09:12 UTC, merged